// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHJ7VeTBcEcYchDCucmbvkWnWdnumKzEA',
    appId: '1:169483559398:web:209eee5c449e50e0db3627',
    messagingSenderId: '169483559398',
    projectId: 'antrun-game',
    authDomain: 'antrun-game.firebaseapp.com',
    storageBucket: 'antrun-game.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-B8d12QF9l9JokB4pz2670MTrWlwEPFU',
    appId: '1:169483559398:android:0dd4dc4b0d6505a1db3627',
    messagingSenderId: '169483559398',
    projectId: 'antrun-game',
    storageBucket: 'antrun-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6a-imt7mwPmvm1rCksB8fGY5ST6LsXQY',
    appId: '1:169483559398:ios:7c4a9ed1ccb2e8eedb3627',
    messagingSenderId: '169483559398',
    projectId: 'antrun-game',
    storageBucket: 'antrun-game.firebasestorage.app',
    iosBundleId: 'com.example.antRun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6a-imt7mwPmvm1rCksB8fGY5ST6LsXQY',
    appId: '1:169483559398:ios:7c4a9ed1ccb2e8eedb3627',
    messagingSenderId: '169483559398',
    projectId: 'antrun-game',
    storageBucket: 'antrun-game.firebasestorage.app',
    iosBundleId: 'com.example.antRun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHJ7VeTBcEcYchDCucmbvkWnWdnumKzEA',
    appId: '1:169483559398:web:684f9e015dfe7fefdb3627',
    messagingSenderId: '169483559398',
    projectId: 'antrun-game',
    authDomain: 'antrun-game.firebaseapp.com',
    storageBucket: 'antrun-game.firebasestorage.app',
  );
}
